version: "3.9"

services:

  app:
    image: mcr.microsoft.com/devcontainers/php:8.4

    working_dir: /workspace/projetLaravel

    volumes:
      - .:/workspace

    command: sleep infinity

    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.4

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest

    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

    ports:
      - "8080:80"

volumes:
  mysql-data:
